[package]
name = "rock_os"
version = "0.1.0"
authors = ["Harshit Ruwali <harshitruwali@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
